global:
 scrape_interval: 3s
 evaluation_interval: 3s
scrape_configs:

 - job_name: 'kafka-connect-host'
   static_configs:
   - targets: ['kafka-connect:9876']

 - job_name: 'yugabyted'
   metrics_path: '/prometheus-metrics'
   static_configs:
   - targets: ['172.165.20.83:9000']



#########################################

#  - job_name: 'yugabyte-n1'
#    metrics_path: '/prometheus-metrics'
#    static_configs:
#    - targets: ['172.151.24.153:9000']

#  - job_name: 'yugabyte-n2'
#    metrics_path: '/prometheus-metrics'
#    static_configs:
#    - targets: ['172.151.67.211:9000']

#  - job_name: 'yugabyte-n3'
#    metrics_path: '/prometheus-metrics'
#    static_configs:
#    - targets: ['172.151.50.88:9000']

#########################################
